### ISSUE TITLE
sync not checking if note / card already exists in deck

### ISSUE THREAD

**Issue by grac-zh** [pavelgordon/babbel2anki-chrome-extension#10]
i was enthusiastic: an extension that is able to sync babbel with anki!

but it is of no use: it doesn't check if it has already synced the words before.
therefore every time i check in anki there are more and more double entries.
very sad!

**Comment by grac-zh** [comment]
new finding: when the vocabulary is set to show 10 items at once, only these 10 items are synced.
when i say: 100 items per page, all items are synced.
what happens, when i have more thant 100 items?
chrome / babbel doesn't allow to show "all" words at once.
and when i log in again, the default is again set to 10 items per page.

this is more than cranky - nowhere to read about.

**Comment by pavelgordon** [comment]
Thanks for the constructive feedback! Indeed there was a bug which caused double entries. Fixed it.

**Comment by pavelgordon** [comment]
Ab

> new finding: when the vocabulary is set to show 10 items at once, only these 10 items are synced.
> when i say: 100 items per page, all items are synced.
> what happens, when i have more than 100 items?
> chrome / babbel doesn't allow to show "all" words at once.
> and when i log in again, the default is again set to 10 items per page.
> 
> this is more than cranky - nowhere to read about.

I updated the readme to make it more clear. 
Basically this extension doesn't have any credentials of your account to Babbel. Instead, it uses information which is already loaded on the page=> thats why only 10(or 100 items) are synced to Anki, and that's why user has to click pages manually in order to sync it.

I am thinking of implementing a different approach, but since it's unofficial extension, there is really not much I can do

**Comment by pavelgordon** [comment]
Please let me know if you have any ideas on how to improve it.
